# Running caribu on a Scene

In [1]:
import numpy as np
from oawidgets.plantgl import PlantGL
from alinea.caribu.CaribuScene import CaribuScene

from openalea.scenemanagement.convert import *

In [2]:
file = "../models/plant3.gltf"
sc = to_pgl(file, verbose=False)

[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -1.00000000e+00  1.22464685e-16  0.00000000e+00]
 [ 0.00000000e+00 -1.22464685e-16 -1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -1.00000000e+00  1.22464685e-16  0.00000000e+00]
 [ 0.00000000e+00 -1.22464685e-16 -1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [3]:
PlantGL(sc)

Plot(antialias=3, axes=['x', 'y', 'z'], axes_helper=1.0, axes_helper_colors=[16711680, 65280, 255], background…

In [4]:
cscene = CaribuScene(sc, scene_unit='m')
raw, agg = cscene.run(direct=True, simplify=True)
pgl_scene, values = cscene.plot(raw['Eabs'],display=False)

v99 = np.percentile(values, 99)
nvalues=np.array(values)
nvalues[nvalues>v99]=v99
values = nvalues.tolist()

In [5]:
PlantGL(pgl_scene, group_by_color=False, property=values)

Plot(antialias=3, axes=['x', 'y', 'z'], axes_helper=1.0, axes_helper_colors=[16711680, 65280, 255], background…